---
title: "2022 Bayer Hooded Sprayer"
author: "Maxwel C Oliveira"
format:
  pdf: 
    theme: simplex
    papersize: letter
    fontsize: 1.1em
    linestretch: 1.7
---


```{r}
#| label: setup
#| include: false
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      fig.align = "center")
```


```{r}
library(tidyverse)
library(drc)
```








```{r}
readxl::read_excel("dataset.xlsx") %>% 
  janitor::clean_names() %>% 
  mutate(rating_dat = as_factor(rating_dat)) %>% 
  mutate_if(is_character, as_factor) -> dat
```





```{r}
dat %>% 
#  filter(rating_dat == 14) %>% 
  ggplot(aes(x = distance_m, y = rating_avg3plants, color = boom)) +
  facet_grid(rating_dat ~ location) +
  geom_point() +
  scale_color_viridis_d() +
  theme_bw() +
  labs(y = "Visual symptomology (%)",
       x = "Distance from field edge (m)")
```


## Wisconsin

### 14 days after application

```{r}
wisc14 <- dat %>% 
  filter(rating_dat == "14" & location == "Wisconsin")
```


```{r}
model_14_wi <- drm(rating_avg3plants ~ distance_m, boom, 
                   fct = EXD.3(), 
                   data = wisc14)
```

```{r}
#| fig-width: 5
#| fig-height: 5

plot(model_14_wi, type = "all", 
     col = c(1,2), 
     pch = 16, log = "",
     xlim = c(0, 50), ylim = c(0,40),
     ylab = "Visual symptomology (%)",
     xlab = "Distance from field edge (m)")

abline(h = 5)
```


```{r}
summary(model_14_wi)
```



```{r}
ED(model_14_wi, c(5, 10, 50, 90))
```



### 28 days after application

```{r}
wisc28 <- dat %>% 
  filter(rating_dat == "28" & location == "Wisconsin")
```

```{r}
model_28_wi <- drm(rating_avg3plants ~ distance_m, boom, fct = EXD.2(), data = wisc28)
```

```{r}
#| fig-width: 5
#| fig-height: 5


plot(model_28_wi, type = "all", 
     col = c(1,2), 
     pch = 16, log = "",
     ylab = "Visual symptomology (%)",
     xlab = "Distance from field edge (m)")
```


```{r}
summary(model_28_wi)
```


```{r}
ED(model_28_wi, c(5, 10, 50, 90))
```

## Missouri

### 14 days after application

```{r}
miss14 <- dat %>% 
  filter(rating_dat == "14" & location == "Missouri") %>% 
  mutate(rating_avg3plants = case_when(
    rating_avg3plants == 0.000000 ~ 0.000001,
    TRUE ~ rating_avg3plants
  ))
```


```{r}
model_14_mo <- drm(rating_avg3plants ~ distance_m, boom, 
                   fct = EXD.2(), 
                   data = miss14)
```

```{r}
#| fig-width: 5
#| fig-height: 5


plot(model_14_mo, type = "all", 
     col = c(1,2), 
     pch = 16, log = "",
     ylab = "Visual symptomology (%)",
     xlab = "Distance from field edge (m)")
```


```{r}
summary(model_14_mo)
```


```{r}
ED(model_14_mo, c(5, 10, 50, 90))
```


### 28 days after application

```{r}
miss28 <- dat %>% 
  filter(rating_dat == "28" & location == "Missouri") %>% 
  mutate(rating_avg3plants = case_when(
    rating_avg3plants == 0.000000 ~ 0.000001,
    TRUE ~ rating_avg3plants
  ))
```


```{r}
model_28_mo <- drm(rating_avg3plants ~ distance_m, boom, 
                   fct = EXD.2(), 
                   data = miss28)
```

```{r}
#| fig-width: 5
#| fig-height: 5


plot(model_28_mo, type = "all", 
     col = c(1,2), 
     pch = 16, log = "",
     ylab = "Visual symptomology (%)",
     xlab = "Distance from field edge (m)")
```


```{r}
summary(model_28_mo)
```


```{r}
summary(model_28_mo)
```



```{r}
ED(model_28_mo, c(5, 10, 50, 90))
```